{{- if .Values.dp.create -}}
{{- $fullName := include "domain-proxy.fullname" . -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "${fullName}-cc-ca" -}}
{{- if not $secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-cc-ca
type: Opaque
data:
{{- $pathca := printf "%s" .Values.dp.configuration_controller.tlsConfig.paths.ca }}
  ca.crt: |
{{ (.Files.Get $pathca) | b64enc | indent 4 }}
{{- end -}}
{{- end }}
